CREATE TABLE MESSAGE_LOG
(
    MESSAGE_ID          UUID PRIMARY KEY,
    TELEGRAM_ID         BIGINT,
    MESSAGE_TEXT        VARCHAR(4096),
    MESSAGE_FULL        JSONB,
    SAVED_INFO          BYTEA
);